# Azure Icons
# Centralized icon definitions for all D2 diagrams
# Icons sourced from https://icons.terrastruct.com/

classes: {
  # General
  resource_group: {
    icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FResource%20Groups.svg
  }

  # Containers
  container_registry: {
    icon: https://icons.terrastruct.com/azure%2FContainer%20Service%20Color%2FContainer%20Registries.svg
  }
  container_app: {
    icon: https://icons.terrastruct.com/azure%2FContainer%20Service%20Color%2FContainer%20Instances.svg
  }
  container_app_environment: {
    icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FApp%20Service%20Environments.svg
  }

  # Networking
  virtual_network: {
    icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FVirtual%20Networks.svg
  }
  subnet: {
    icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FVirtual%20Network%20%28Classic%29.svg
  }
  private_endpoint: {
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAPI%20Management%2FCloud%20Endpoints.svg
  }
  dns_zone: {
    icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FDNS%20Zones.svg
  }

  # Databases
  cosmos_db: {
    icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Cosmos%20DB.svg
  }

  # Storage
  storage_account: {
    icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FStorage%20Accounts.svg
  }

  # Security
  key_vault: {
    icon: https://icons.terrastruct.com/azure%2FSecurity%20Service%20Color%2FKey%20Vaults.svg
  }

  # Monitor
  log_analytics: {
    icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FLog%20Analytics%20Workspaces.svg
  }
  app_insights: {
    icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FApplication%20Insights.svg
  }

  # Identity
  entra_id: {
    icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FTwo%20User%20Icon.svg
  }
  users: {
    icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FUser%20Icon.svg
  }
}
