# Azure Icons
# Centralized icon definitions for all D2 diagrams
# Icons sourced from https://icons.terrastruct.com/

classes: {
  # General
  resource_group: {
    icon: https://icons.terrastruct.com/azure%2FGeneral%2F10002-icon-service-Resource-Groups.svg
  }
  
  # Containers
  container_registry: {
    icon: https://icons.terrastruct.com/azure%2FContainers%2F10105-icon-service-Container-Registries.svg
  }
  container_app: {
    icon: https://icons.terrastruct.com/azure%2FContainers%2F10103-icon-service-Container-Apps.svg
  }
  container_app_environment: {
    icon: https://icons.terrastruct.com/azure%2FContainers%2F10104-icon-service-Container-Apps-Environments.svg
  }
  
  # Networking
  virtual_network: {
    icon: https://icons.terrastruct.com/azure%2FNetworking%2F10061-icon-service-Virtual-Networks.svg
  }
  subnet: {
    icon: https://icons.terrastruct.com/azure%2FNetworking%2F10073-icon-service-Subnets.svg
  }
  private_endpoint: {
    icon: https://icons.terrastruct.com/azure%2FNetworking%2F10064-icon-service-Private-Link.svg
  }
  dns_zone: {
    icon: https://icons.terrastruct.com/azure%2FNetworking%2F10065-icon-service-DNS-Zones.svg
  }
  
  # Databases
  cosmos_db: {
    icon: https://icons.terrastruct.com/azure%2FDatabases%2F10124-icon-service-Azure-Cosmos-DB.svg
  }
  
  # Storage
  storage_account: {
    icon: https://icons.terrastruct.com/azure%2FStorage%2F10086-icon-service-Storage-Accounts.svg
  }
  
  # Security
  key_vault: {
    icon: https://icons.terrastruct.com/azure%2FSecurity%2F10245-icon-service-Key-Vaults.svg
  }
  
  # Monitor
  log_analytics: {
    icon: https://icons.terrastruct.com/azure%2FMonitor%2F00004-icon-service-Log-Analytics-Workspaces.svg
  }
  app_insights: {
    icon: https://icons.terrastruct.com/azure%2FMonitor%2F00009-icon-service-Application-Insights.svg
  }
  
  # Identity
  entra_id: {
    icon: https://icons.terrastruct.com/azure%2FIdentity%2F10221-icon-service-Azure-Active-Directory.svg
  }
  users: {
    icon: https://icons.terrastruct.com/azure%2FIdentity%2F10215-icon-service-Users.svg
  }
}
