# Virtual Network and Subnets

...@icons

vnet: Virtual Network\n(prod) {
  class: virtual_network
  
  container_apps_subnet: Container Apps\nSubnet {
    class: subnet
  }
  
  database_subnet: Database\nSubnet {
    class: subnet
  }
  
  storage_subnet: Storage\nSubnet {
    class: subnet
  }
}
