# Virtual Network and Subnets

vnet: Virtual Network\n(prod) {
  icon: https://icons.terrastruct.com/azure%2FNetworking%2F10061-icon-service-Virtual-Networks.svg
  
  container_apps_subnet: Container Apps\nSubnet {
    icon: https://icons.terrastruct.com/azure%2FNetworking%2F10073-icon-service-Subnets.svg
  }
  
  database_subnet: Database\nSubnet {
    icon: https://icons.terrastruct.com/azure%2FNetworking%2F10073-icon-service-Subnets.svg
  }
  
  storage_subnet: Storage\nSubnet {
    icon: https://icons.terrastruct.com/azure%2FNetworking%2F10073-icon-service-Subnets.svg
  }
}
