# Shared Resources
# These resources are used by both dev and prod environments

shared_rg: Resource Group\n(shared) {
  icon: https://icons.terrastruct.com/azure%2FGeneral%2F10002-icon-service-Resource-Groups.svg
}

acr: Azure Container Registry\n(acrctkshared) {
  icon: https://icons.terrastruct.com/azure%2FContainers%2F10105-icon-service-Container-Registries.svg
  shape: cylinder
}

# Shared resource relationships
shared_rg -> acr: contains
