# Shared Resources
# These resources are used by both dev and prod environments

...@icons

shared_rg: Shared Resource Group {
  class: resource_group
  
  acr: Azure Container Registry {
    class: container_registry
    shape: cylinder
  }
}
