# Supporting Services

...@icons

key_vault: Key Vault {
  class: key_vault
}

storage_account: Storage Account {
  class: storage_account
  shape: cylinder
}

log_analytics: Log Analytics\nWorkspace {
  class: log_analytics
}

app_insights: Application Insights {
  class: app_insights
}

# Supporting service relationships
app_insights -> log_analytics: sends logs to
